# Generated by Django 2.2.16 on 2023-05-25 08:53
import csv
import os

from django.db import migrations


def load_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    file_path = os.path.join('fixtures', 'ingredients.csv')
    with open(file_path, encoding='utf-8') as file:
        reader = csv.reader(file)
        for name, measurement_unit in reader:
            Ingredient.objects.get_or_create(
                name=name, measurement_unit=measurement_unit
            )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [migrations.RunPython(load_ingredients)]
